// Code generated by qtc from "hello.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line hello.qtpl:1
package template

//line hello.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line hello.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line hello.qtpl:1
func StreamGetPRCommentContent(qw422016 *qt422016.Writer, comment PRCommentData) {
//line hello.qtpl:1
	qw422016.N().S(`
<img align="right" src="`)
//line hello.qtpl:2
	qw422016.E().S(comment.CommitByCommitReviewScoreImgUrl)
//line hello.qtpl:2
	qw422016.N().S(`" alt="Score: `)
//line hello.qtpl:2
	qw422016.N().FPrec(float64(comment.CommitByCommitReviewScore), 2)
//line hello.qtpl:2
	qw422016.N().S(`"/>

Best reviewed: `)
//line hello.qtpl:4
	if comment.BestReviewedCommitByCommit {
//line hello.qtpl:4
		qw422016.N().S(` **commit by commit** `)
//line hello.qtpl:4
	} else {
//line hello.qtpl:4
		qw422016.N().S(` **with all changes**`)
//line hello.qtpl:4
	}
//line hello.qtpl:4
	qw422016.N().S(`
___
<details>
<summary>
Optimal code review plan `)
//line hello.qtpl:9
	if comment.OptimalCodeReviewWarningsCount > 0 || comment.OptimalCodeReviewSquashedCommitsCount > 0 {
//line hello.qtpl:9
		qw422016.N().S(`(`)
//line hello.qtpl:11
		if comment.OptimalCodeReviewWarningsCount == 1 {
//line hello.qtpl:11
			qw422016.N().D(comment.OptimalCodeReviewWarningsCount)
//line hello.qtpl:11
			qw422016.N().S(` `)
//line hello.qtpl:11
			qw422016.N().S(`warning`)
//line hello.qtpl:11
		}
//line hello.qtpl:12
		if comment.OptimalCodeReviewWarningsCount > 1 {
//line hello.qtpl:12
			qw422016.N().D(comment.OptimalCodeReviewWarningsCount)
//line hello.qtpl:12
			qw422016.N().S(` `)
//line hello.qtpl:12
			qw422016.N().S(`warnings`)
//line hello.qtpl:12
		}
//line hello.qtpl:13
		if comment.OptimalCodeReviewWarningsCount > 0 && comment.OptimalCodeReviewSquashedCommitsCount > 0 {
//line hello.qtpl:13
			qw422016.N().S(`,`)
//line hello.qtpl:13
			qw422016.N().S(` `)
//line hello.qtpl:13
		}
//line hello.qtpl:14
		if comment.OptimalCodeReviewSquashedCommitsCount == 1 {
//line hello.qtpl:14
			qw422016.N().D(comment.OptimalCodeReviewSquashedCommitsCount)
//line hello.qtpl:14
			qw422016.N().S(` `)
//line hello.qtpl:14
			qw422016.N().S(`commit squashed`)
//line hello.qtpl:14
		}
//line hello.qtpl:15
		if comment.OptimalCodeReviewSquashedCommitsCount > 1 {
//line hello.qtpl:15
			qw422016.N().D(comment.OptimalCodeReviewSquashedCommitsCount)
//line hello.qtpl:15
			qw422016.N().S(` `)
//line hello.qtpl:15
			qw422016.N().S(`commits squashed`)
//line hello.qtpl:15
		}
//line hello.qtpl:15
		qw422016.N().S(`)`)
//line hello.qtpl:17
	}
//line hello.qtpl:18
	qw422016.N().S(`
<br/>
<br/>
</summary>
   `)
//line hello.qtpl:22
	for _, commit := range comment.OptimalCodeReview {
//line hello.qtpl:22
		qw422016.N().S(`
    `)
//line hello.qtpl:23
		if len(commit.Warnings) > 0 || len(commit.SquashedCommits) > 0 {
//line hello.qtpl:23
			qw422016.N().S(`
<details>
<summary>
<a href="`)
//line hello.qtpl:26
			qw422016.E().S(commit.CommitUrl)
//line hello.qtpl:26
			qw422016.N().S(`">`)
//line hello.qtpl:26
			qw422016.E().S(commit.CommitName)
//line hello.qtpl:26
			qw422016.N().S(`</a>
`)
//line hello.qtpl:27
			if len(commit.SquashedCommits) > 0 {
//line hello.qtpl:27
				qw422016.N().S(`
<img align="right" src="https://pullassistant.com/assets/merge.png"/>
`)
//line hello.qtpl:29
			}
//line hello.qtpl:29
			qw422016.N().S(`
`)
//line hello.qtpl:30
			if len(commit.Warnings) > 0 {
//line hello.qtpl:30
				qw422016.N().S(`
<img align="right" src="https://pullassistant.com/assets/warning.png"/>
`)
//line hello.qtpl:32
			}
//line hello.qtpl:32
			qw422016.N().S(`
</summary>
<br/>

        `)
//line hello.qtpl:36
			if len(commit.SquashedCommits) > 0 {
//line hello.qtpl:36
				qw422016.N().S(`
> Squashed `)
//line hello.qtpl:37
				qw422016.N().D(len(commit.SquashedCommits))
//line hello.qtpl:37
				qw422016.N().S(` commits:
            `)
//line hello.qtpl:38
				for _, squashedCommit := range commit.SquashedCommits {
//line hello.qtpl:38
					qw422016.N().S(`
> - <a href="`)
//line hello.qtpl:39
					qw422016.E().S(squashedCommit.CommitUrl)
//line hello.qtpl:39
					qw422016.N().S(`">`)
//line hello.qtpl:39
					qw422016.E().S(squashedCommit.CommitName)
//line hello.qtpl:39
					qw422016.N().S(`</a>
            `)
//line hello.qtpl:40
				}
//line hello.qtpl:40
				qw422016.N().S(`
        `)
//line hello.qtpl:41
			}
//line hello.qtpl:41
			qw422016.N().S(`


        `)
//line hello.qtpl:44
			if len(commit.Warnings) > 0 {
//line hello.qtpl:44
				qw422016.N().S(`
            `)
//line hello.qtpl:45
				for _, warning := range commit.Warnings {
//line hello.qtpl:45
					qw422016.N().S(`
> `)
//line hello.qtpl:45
					qw422016.N().S("`")
//line hello.qtpl:46
					qw422016.E().S(warning.FileName)
//line hello.qtpl:46
					qw422016.N().S(``)
//line hello.qtpl:46
					qw422016.N().S("`")
//line hello.qtpl:46
					qw422016.N().S(` `)
//line hello.qtpl:46
					qw422016.N().FPrec(float64(warning.Interference*100), 0)
//line hello.qtpl:46
					qw422016.N().S(`% changes removed in <a href="`)
//line hello.qtpl:46
					qw422016.E().S(warning.InterferingCommitUrl)
//line hello.qtpl:46
					qw422016.N().S(`">`)
//line hello.qtpl:46
					qw422016.E().S(warning.InterferingCommitName)
//line hello.qtpl:46
					qw422016.N().S(`</a>
            `)
//line hello.qtpl:47
				}
//line hello.qtpl:47
				qw422016.N().S(`
        `)
//line hello.qtpl:48
			}
//line hello.qtpl:48
			qw422016.N().S(`
</details>
    `)
//line hello.qtpl:50
		} else {
//line hello.qtpl:50
			qw422016.N().S(`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="`)
//line hello.qtpl:51
			qw422016.E().S(commit.CommitUrl)
//line hello.qtpl:51
			qw422016.N().S(`">`)
//line hello.qtpl:51
			qw422016.E().S(commit.CommitName)
//line hello.qtpl:51
			qw422016.N().S(`</a>
   `)
//line hello.qtpl:52
		}
//line hello.qtpl:52
		qw422016.N().S(`
   `)
//line hello.qtpl:53
	}
//line hello.qtpl:53
	qw422016.N().S(`
</details>

> Powered by [Pull Assistant](https://pullassistant.com). Last update [`)
//line hello.qtpl:56
	qw422016.E().S(comment.LastUpdateFromText)
//line hello.qtpl:56
	qw422016.N().S(`](`)
//line hello.qtpl:56
	qw422016.E().S(comment.LastUpdateFromUrl)
//line hello.qtpl:56
	qw422016.N().S(`) ... [`)
//line hello.qtpl:56
	qw422016.E().S(comment.LastUpdateToText)
//line hello.qtpl:56
	qw422016.N().S(`](`)
//line hello.qtpl:56
	qw422016.E().S(comment.LastUpdateToUrl)
//line hello.qtpl:56
	qw422016.N().S(`). Read the [comment docs](https://pullassistant.com).
`)
//line hello.qtpl:57
}

//line hello.qtpl:57
func WriteGetPRCommentContent(qq422016 qtio422016.Writer, comment PRCommentData) {
//line hello.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line hello.qtpl:57
	StreamGetPRCommentContent(qw422016, comment)
//line hello.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line hello.qtpl:57
}

//line hello.qtpl:57
func GetPRCommentContent(comment PRCommentData) string {
//line hello.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line hello.qtpl:57
	WriteGetPRCommentContent(qb422016, comment)
//line hello.qtpl:57
	qs422016 := string(qb422016.B)
//line hello.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line hello.qtpl:57
	return qs422016
//line hello.qtpl:57
}
